name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^3.1.0+1
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  fluro: ^1.5.1
  json_annotation: ^2.0.0
  connectivity: ^0.4.2
  dio: ^3.0.0
  event_bus: ^1.0.3
  http: '>=0.11.3+12'
  json2entity: 1.0.6
  # 权限获取
  permission_handler: '^3.2.2'
  # 安装apk
  #  install_plugin: ^2.0.1
  open_file: ^2.1.1
  # 下载
  #  flutter_downloader: ^1.3.3
  # 存储新安装包

  path_provider: ^1.4.5
  # 获取本地版本号
  package_info: ^0.4.0+3
  url_launcher: ^5.4.1
  fluttertoast: ^3.1.3
  # 刷新加载
  pull_to_refresh: ^1.5.7
  flutter_easyrefresh: ^2.0.4
  pull_to_refresh_notification: ^0.3.3
  # 瀑布流
  flutter_staggered_grid_view: '^0.3.0'
  # NestedScrollView扩展
  extended_nested_scroll_view: ^0.3.8
  # 仿iOS tableView
  flutter_section_table_view: ^1.0.5
  flutter_tableview: ^1.0.1
  # 分享
  share: ^0.6.1+1
  # 记住密码
  shared_preferences: ^0.5.0
  # 数据持久化
  sqflite: ^1.1.7+3
  # 轮播图
  flutter_swiper: ^1.0.6
  #webview
  webview_flutter: ^0.3.16
  flutter_webview_plugin: ^0.3.9+1

  #图片缓存插件
  cached_network_image: any

  flutter_spinkit: '^4.1.0' # loading 框
  flutter_picker: ^1.1.0
  # oktoast: ^2.2.0
  #  json动画播放
  flutter_lottie: ^0.2.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3

  image_picker: ^0.6.2+1

  audioplayers: ^0.13.1

  time: '^1.2.0'

  # 原生view
#  platform_view:
#    path: ./platform_view
  # 一个简单的透明图像。表示为Uint8List，它最初是从Flutter代码基中提取的(在测试包中是私有的)。
  transparent_image: ^1.0.0

dev_dependencies:
  build_runner: ^1.7.0
  json_serializable: ^3.1.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/jsonplay/
    - assets/image/
    - images/

    - data/province.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
